[tool.poetry]
name = "actions"
version = "0.1.0"
description = ""
authors = ["ulurn-av <ulurn@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
setuptools = "^70.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
